apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksdemo-deployment
  labels:
    app: eksdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eksdemo
  template:
    metadata:
      labels:
        app: eksdemo
    spec:
      containers:
        - name: eksdemo
          image: ghcr.io/kemalates/eks-demo:latest
          ports:
            - containerPort: 80
